name: CD

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ secrets.GHCR_USERNAME }}/myapp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push image to GHCR
        run: docker push $IMAGE_NAME

      - name: Deploy on remote Oracle VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/myapp
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
            docker pull $IMAGE_NAME
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp -p 8080:8080 $IMAGE_NAME
