name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t myapp-image .

      - name: Save Docker image to TAR
        run: |
          mkdir -p tmp-docker
          docker save myapp-image -o tmp-docker/myapp.tar

      - name: Upload Docker image tar to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: tmp-docker/myapp.tar
          target: ~/app/

      - name: Run Docker container on remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            cd ~/app
            docker stop myapp || true
            docker rm myapp || true
            docker load -i myapp.tar
            docker run -d --name myapp -p 8080:8080 myapp-image